apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ceph-csi-cephfs-snapclass
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
driver: rook-ceph.cephfs.csi.ceph.com
deletionPolicy: Delete
parameters:
  # Specify any ceph specific parameters if needed
  clusterID: rook-ceph
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
