
# Get the dashboard password for the user "admin" (generated by rook)
DASHBOARD_PASSWORD=$(kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode)
echo "Ceph dashboard password for user 'admin': $DASHBOARD_PASSWORD"
echo "Dashboard should be accessible at http://localhost:8443"

kubectl port-forward service/rook-ceph-mgr-dashboard 8443:8443 -n rook-ceph
