
# get the password for the user "admin" (generated by rook)
echo Usename: admin
echo Password: $(kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode && echo)

kubectl port-forward service/rook-ceph-mgr-dashboard 8443:8443 -n rook-ceph
